excluded:
  - Example
  - Tests
  - Library/Tests
  - Carthage
  - Pods
  - Sources/Utils/Reachability.swift
  - Library/Sources/Utils/Reachability.swift
  - UI/macOS/Components/JSSwitch.swift
  - Library/UI/macOS/Components/JSSwitch.swift

disabled_rules:
  - void_return
  - notification_center_detachment
  - block_based_kvo

opt_in_rules:
  - force_unwrapping
  - object_literal
  - private_outlet
  - explicit_init
  - overridden_super_call
  - switch_case_on_newline
  - empty_count
  - redundant_nil_coalescing
  - nimble_operator
  - closure_end_indentation
  - file_header
  - first_where
  - prohibited_super_call
  - fatal_error_message
  - implicitly_unwrapped_optional
  # - explicit_type_interface
  - operator_usage_whitespace
  - number_separator
  # - missing_docs
  - closure_spacing
  - implicit_return
  # - conditional_returns_on_newline
  - unneeded_parentheses_in_closure_argument
  # - let_var_whitespace
  # - extension_access_modifier
  # - explicit_top_level_acl
  - vertical_parameter_alignment_on_call
  - unused_optional_binding
  # - multiline_parameters
  - contains_over_first_not_nil
  - attributes
  # - explicit_enum_raw_value
  # - explicit_top_level_acl
  - joined_default_parameter
  # - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - no_extension_access_modifier
  - no_grouping_extension
  - pattern_matching_keywords
  - quick_discouraged_call
  - single_test_class
  - sorted_imports
  - strict_fileprivate
  # - trailing_closure
  - discouraged_object_literal
  # - discouraged_optional_boolean
  # - explicit_acl

file_length:
  warning: 500
  error: 1000
line_length:
  warning: 120
function_body_length:
  warning: 100
  error: 150
identifier_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 40
    error: 60
type_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 50
    error: 60
statement_position:
  statement_mode: uncuddled_else
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
colon:
  flexible_right_spacing: true
large_tuple:
  warning: 5
  error: 8
